# Generated by Django 5.0.1 on 2024-02-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_left',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_left', models.CharField(max_length=20)),
                ('small_price_left', models.CharField(max_length=20)),
                ('big_price_left', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product_right',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_right', models.CharField(max_length=20)),
                ('small_price_right', models.CharField(max_length=20)),
                ('big_price_right', models.CharField(max_length=20)),
            ],
        ),
    ]
