# Generated by Django 5.0.1 on 2024-02-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_left',
            name='image_left',
            field=models.ImageField(default=1, upload_to='products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_right',
            name='image_right',
            field=models.ImageField(default=1, upload_to='products'),
            preserve_default=False,
        ),
    ]
